### ISSUE TITLE
enhancement: support for swagger API definition?

### ISSUE THREAD

**Issue by Kosta-Github** [tikalk/commandcar#1]
see: http://swagger.io/

**Comment by shaharsol** [comment]
Excellent idea! will look into it.

**Comment by g-div** [comment]
[api-models](https://github.com/APIs-guru/api-models) is a repository of Swagger specifications for a lot of API. Once the application supports the Swagger API definition, you can automatically access all of them !!!

Take a look at it ;)

Edit:
I've just read about #3

**Comment by shaharsol** [comment]
great find!

**Comment by shaharsol** [comment]
new version of commandcar not only supports swagger2.0, it actually relies on it. Also uses api-models.

**Comment by Kosta-Github** [comment]
:+1: Nice, now I will give it a try...
