### ISSUE TITLE
Installation on mac fails?

### ISSUE THREAD

**Issue by mkarliner** [tikalk/commandcar#2]
After installing (npm install -g commandcar), and running commandcar with no arguments I get

error building db: Error: ENOENT, no such file or directory '/usr/local/lib/node_modules/commandcar/node_modules/@commandcar'

**Comment by shaharsol** [comment]
You need to install it with sudo, since its a global installation and things need to be copied into /usr

**Comment by joaocc** [comment]
Hi,
I also have this problem in Mac, with a very common setup based on nvm that doesn't require root.
None of my other 100+ globally installed packages require it.
Globally installed packages end up going under  ~/.node/lib/node_modules/
I guess the target folder should be generated in a more general manner.
Thx

**Comment by shaharsol** [comment]
@mkarliner regardless of sudo yes/no right now, I think what you're seeing is just a debug log that was left behind. There really is no such folder if you never installed any API (the 1st install command creates that folder, which is actually a npm scope). Can you try running commandcar --help and see if you get the desired output?

And sorry for misleading with the sudo thing, which maybe a problem on its own apparently.

**Comment by joaocc** [comment]
```
$ commandcar --help

  Usage: commandcar [options] [command]


  Commands:

    load [options]    
    install [options] 

  Options:

    -h, --help  output usage information
```

**Comment by joaocc** [comment]
Also, not sure if this helps, but this is the output of npm-lazy when running `commandcar install ...`, which I am using as a local proxy:

```
app debug [GET] https://registry.npmjs.org/@commandcar%2ffacebook
app error [404] Error:  { [Error: URL is not in the npm_lazy cache, and it cannot be fetched (max retries exhausted): https://registry.npmjs.org/@commandcar%2ffacebook]
  statusCode: 404,
  contentStream: null,
  content: '{"error":"Not found"}' }
```

My idea is that it could be a cause or simply a correlated error.

**Comment by shaharsol** [comment]
@joaocc yeah that what it should ouput. 

as for your 2nd comment, there's actually no such package @commandcar/facebook (yet, there will be as soon as somebody define it ;-) ), it was just given as an example in the readme file.

**Comment by joaocc** [comment]
hum... that might explain my error.
Is there anything I can install at this point to test this?
Thx!

**Comment by shaharsol** [comment]
instagram and google_accounts

**Comment by shaharsol** [comment]
Became irrelevant with the new v0.1.1 which relies on swagger2.0.
