### ISSUE TITLE
APIs.guru integration

### ISSUE THREAD

**Issue by IvanGoncharov** [tikalk/commandcar#3]
I like your idea about having API collection, because I'm working on very [similar project](https://github.com/APIs-guru/api-models).
I'm trying to create open catalog of API specification, right now it has 172 specs including all Google services, Trello, Instagram, Spotify, etc.
All specs are validated and also keep in sync with their source, which is official API docs in almost all cases.
But more importantly I have an [API](https://github.com/APIs-guru/api-models/blob/master/API.md) and it already used by other projects:
- https://any-api.com
- https://sdks.io
- http://www.cenit.io
- https://www.corezoid.com (In progress)

Integration with your tool is very interesting for me.
If you interested and want to discuss it further we can chat in [Gitter](https://gitter.im/APIs-guru/api-models) or you can call me in Skype: ivangon4arov

**Comment by shaharsol** [comment]
Sure, I will look into it.

**Comment by shaharsol** [comment]
integrated in v0.1.1

**Comment by IvanGoncharov** [comment]
@shaharsol  Thanks :+1: 
I added `commandcar` to list of integrations: https://github.com/APIs-guru/api-models/blob/master/README.md#integration-with-3rd-party-services
Please check it.
