### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by cad** [tikalk/commandcar#4]
Will this project support GraphQL based APIs?

**Comment by shaharsol** [comment]
The new v0.1.1 version relies on swagger. Never dove deeply into GraphQL. Do you have any idea if a swagger-GraphQL integration is possible?

**Comment by cad** [comment]
Well swagger is all about REST and GraphQL is all about not being REST. With the 2.0 swagger specification I think it is not possible so it should be supported exclusively.

**Comment by cad** [comment]
I guess the answer is no. So closing this.
