### ISSUE TITLE
Invalid JSON in instagram example

### ISSUE THREAD

**Issue by dalhundal** [tikalk/commandcar#5]
All bar one of the files in `commandcar/apis/instagram/commands` are missing an doublequote 

![download](https://cloud.githubusercontent.com/assets/560101/11420651/550a31cc-9427-11e5-8af4-f216370f68f7.jpg)

Also, the `users_get.json` file there mentions "facebook user id", should this be "instagram user id"?

**Comment by dalhundal** [comment]
You missed one in - `commandcar/apis/instagram/commands/users_media_recent.json`

Also, it seems that in all the JSON files you have trailing commas which cause the JSON to be invalid.

For example you have:

```
{
    "a": "b",
    "c": "d",
}
```

and there should be no trailing comma after "d".

**Comment by shaharsol** [comment]
You're right about that missing ", thanks!

As for the json, I used [jsonic](https://github.com/rjrodger/jsonic) for parsing, so practically it isn't a problem. It does render better on github when it's valid. Do you see any point in demanding valid json in the definition files?

**Comment by dalhundal** [comment]
Yeah, I think it's pretty important to use valid JSON - the built in `JSON.parse()` (in fact, any proper JSON parser) cannot parse those files as is. The only reason it's working for you is that you're using _jsonic_ which seems to exist purely to allow you to use invalid JSON.

It seems odd that you'd include a third party library specifically so you could get away with invalid JSON, whereas by sticking to the correct syntax (in this case, its so little pain - just a case of removing some commas) you could just use the methods already provided by Javascript and skip the dependency.
