### ISSUE TITLE
enhancement: support for RAML API definition?

### ISSUE THREAD

**Issue by joaocc** [tikalk/commandcar#7]
This is a natural follow up to issue #1.
Swagger and RAML seem to be the most used formats for API specification and generation.
Thx

**Comment by IvanGoncharov** [comment]
I can suggest using [api-spec-converter](https://github.com/lucybot/api-spec-converter) lib currently it support convetion of Swagger 1.x, I/O Docs, API Blueprint, Google API Discovery, RAML and WADL into
Swagger 2.0 format.

**Comment by shaharsol** [comment]
thx!

**Comment by shaharsol** [comment]
v0.1.1 now relies on swagger2.0. I assume any RAML can be easily converted into swagger2.0 using the above mentioned tool
